; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200


board_microros_distro = humble
board_microros_transport = serial

# Load variables directly from the omnimow.env environment file during compilation
build_flags =
    -D TRACK_WIDTH=${sysenv.OMNIMOW_TRACK_WIDTH}
    -D VESC_LEFT_ID=${sysenv.OMNIMOW_VESC_LEFT_ID}
    -D VESC_RIGHT_ID=${sysenv.OMNIMOW_VESC_RIGHT_ID}

# Uses the pre-compiled micro-ROS Arduino library to avoid Windows build errors
lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio.git