; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

# We use the precompiled Arduino version to avoid Windows build issues.
# NOTE: If PlatformIO has trouble resolving the micro-ROS library, verify the ESP32 toolchain and library cache.
lib_deps = 
    https://github.com/micro-ROS/micro_ros_platformio.git

build_flags = 
    -L${PROJECT_DIR}/.pio/libdeps/esp32dev/micro_ros_arduino/src/esp32/
    -lmicroros
    -D TRACK_WIDTH=${sysenv.NUROMOW_TRACK_WIDTH}
    -D VESC_LEFT_ID=${sysenv.NUROMOW_VESC_LEFT_ID}
    -D VESC_RIGHT_ID=${sysenv.NUROMOW_VESC_RIGHT_ID}