[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

# Uses the pre-compiled micro-ROS Arduino library to avoid Windows build errors
lib_deps = 
    https://github.com/micro-ROS/micro_ros_arduino.git

build_flags = 
    -L${PROJECT_DIR}/.pio/libdeps/esp32dev/micro_ros_arduino/src/esp32/
    -lmicroros