name: OmniMow Docker Build og Udgivelse

on:
  push:
    branches: [ "main" ]

jobs:
  build-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: [stereo_vision, depth_fusion, docking_control, app_backend, rosbridge_websocket]
    steps:
    - name: Hent kildekode (Checkout)
      uses: actions/checkout@v4

    - name: Opsæt QEMU (Muliggør cross-compilation til arm64)
      uses: docker/setup-qemu-action@v3

    - name: Opsæt Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log ind på GHCR (GitHub Container Registry)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Compiler og udgiv ${{ matrix.service }} Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./${{ matrix.service }}
        platforms: linux/arm64
        push: true
        tags: ghcr.io/${{ github.repository }}/${{ matrix.service }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max