- name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install PlatformIO Core (creates the virtual environment)
      run: |
        curl -fsSL https://raw.githubusercontent.com/platformio/platformio-core-installer/master/get-platformio.py -o get-platformio.py
        python3 get-platformio.py
        # Add the PlatformIO environment to the GitHub Actions PATH
        echo "$HOME/.platformio/penv/bin" >> $GITHUB_PATH

    - name: Build ESP32 Drive Controller Firmware
      run: |
        pio run -d ./esp32_code/Drive_controller
